#!/bin/sh
#for f in "$@"; do
#  u=$(printf "%s" "$f" | sed "s|%|%25|g" | sed "s|?|%3F|g" | sed "s|#|%23|g")
#  unzip -Z -1 "$f" '*/' | while read s; do
#    [ -z ${s#*/} ] && cat "${u}/${s}index.rdf"
#  done
#done

File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
folder=$(unzip -Z -1 "$1" '*/')
unzip "$1"
tts "$1" && cat $folder'index.rdf' >> "$File".md && rm -r $folder

