#!/bin/bash
folder="$1"
#ls --hide=*.md "$folder" > f
list=$(ls -1 --hide=*.md "$folder")
foldertxt=${folder%.*}
#echo $list
#echo "$FolderSync"/
lines="$(wc --lines <<< "$list")"

for (( i=$lines ; i>=1 ; i-- ));
do
	element=$(sed -n "${i}p" <(echo "$list"))
	echo "$element"
	#f=$(basename $element)
	#for f in $list;
	#do
	File=$(echo "$element" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
	mv -n "$folder"/"$element" "$folder"/"$File"
	g=$(basename "$File")
	extens=${g##*.}
	Filena=${File%.*}
	extenspdf=$(echo $File | grep -o pdf)
	extensxopp=$(echo $File | grep -o xopp)
	extensmp4=$(echo $File | grep -o mp4)
	extensmov=$(echo $File | grep -o mov)
	extensmkv=$(echo $File | grep -o mkv)
	extensflv=$(echo $File | grep -o flv)
	Unterricht=$(echo $File | grep -o Unterrichtsnotiz)

	if [[ $(echo $File | grep -o Unterrichtsnotiz) == Unterrichtsnotiz || $(echo $File | grep -o Unterrichtsnotizen) == Unterrichtsnotizen ]]
	then
		source="Christian Gößl"
		tags="@Unterricht @Nachhilfe"
		additiontext=""
	fi
	function Wikiprev(){
		touch "$folder"/"$File".md
		echo "Content-Type: text/x-zim-wiki" >> "$folder"/"$File".md
		echo "Wiki-Format: zim 0.6" >> "$folder"/"$File".md
		echo "===== $File =====" >> "$folder"/"$File".md
		echo "Wiki-Format: zim 0.6" >> "$folder"/"$File".md
	}

	function Timestamps(){
		echo "Text creation time: $(date +"[[Zettelkasten:%Y:%m:%d]]")" >> "$folder"/"$File".md
		echo "Modification time: $(date +"[[Zettelkasten:%Y:%m:%d]]" -r "$folder"/"$g")" >> "$folder"/"$File".md
	}

	if [ -e "$folder"/"$File".md ];
	then
		echo no
	else
		if [[ pdf == $extens ]]
		then
			#echo pdf
			ttpdf "$folder"/"$g" "$source" "$tags" "$additiontext"
		elif [[ JPEG == $extens || jpg == $extens || png == $extens || webp == $extens || jpeg == $extens || svg == $extens ]] && [[ -z $extenspdf && -z $extensxopp && -z $extensmp4 && -z $extensmov && -z $extensflv && -z $extensmkv ]]
		then
			#echo pic
			ttpic "$folder"/"$g" "$source" "$tags" "$additiontext"
			#echo yes
		elif [[ mp4 == $extens || mov == $extens || mkv == $extens || flv = $extens ]]
		then
			#echo vid
			#ttdown "$folder"/"$g" "$2"
			filena=${g%.*} #only the filename
			if [[ -e "$filena".md && ! -d "$filena" ]];
			then
			ttvidc "$Filename"
		fi
			Wikiprev
			echo "[*] @VIDEO $tags **[[../$Filename]]** $source" >> "$File".md
			Timestamps
			ffmpeg -loglevel quiet -ss 2 -i "$File"  -t 1 -f image2 "$File".png
			convert "$File".png -resize 1200x1200 -quality 97 "$File"-px.png
			mv "$File"-px.png "$File".png
			echo -e "[[../]]\n$2" >> "$File".md
			echo -e "\n{{../$File.png?width=750}}\n" >> "$File".md
			echo "$3" >> "$File".md
		elif [[ epub == $extens ]]
		then
			Wikiprev
			echo "[*] @EBOOK $3 **[[../$f]] $2**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$2\n" >> "$folder"/"$File".md
			einfo "$folder"/"$g" >> "$folder"/"$File".md
			#Opentxt
		elif [[ eml == $extens ]]
		then
			Wikiprev
			echo "[*] @EMAIL $3 **[[../$f]] $2**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$2\n" >> "$folder"/"$File".md
			cat "$folder"/"$g" >> "$folder"/"$File".md
			#Opentxt
		elif [[ maff == $extens ]]
		then
			Wikiprev
			folder2=$(unzip -Z -1 "$g" '*/')
			unzip "$f"
			echo "[*] @WEB $3 **[[../$f]] $2 $(cat $folder/$folder2'index.dat' | grep source | cut -f 2)**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$2\n" >> "$folder"/"$File".md
			cat "$folder"/$folder'index.rdf' >> "$folder"/"$File".md
			#pandoc -f html -t zimwiki $folder'index.html' >> "$File".md
			rm -r "$folder"/"$folder2"
			#Opentxt
		elif [[ $extens == xopp ]]
		then
			echo xopp
			filename=$(basename "$folder"/"$File" .xopp)
			Wikiprev
			echo "[*] $tags **[[../$Filename]] $source**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$additiontext\n" >> "$folder"/"$File".md
			xournalpp --export-range=1 "$folder"/"$File" -i "$folder"/"$File".png
			echo -e "{{../$File.png?width=750}}\n" >> "$folder"/"$File".md
			#xournalpp "$folder"/"$File" -p "$folder"/"$filename".pdf
			#ttpdf "$folder"/"$filename".pdf
		elif [[ -n $extenspdf || -n $extensxopp || -z $extensmp4 || -z $extensmov || -z $extensflv || -z $extensmkv ]]
		then
			echo "tue nichts"
		elif [[ $extens == $g ]]
		then
			Wikiprev
			echo "[*] @ORDNER $3 **[[../$g]] $2**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$2\n" >> "$folder"/"$File".md
			#Opentxt
		else
			#echo else
			Wikiprev
			echo "[*] $3 **[[../$g]] $2**" >> "$folder"/"$File".md
			Timestamps
			echo -e "[[../]]\n$2\n" >> "$folder"/"$File".md
			#Opentxt
		fi

	fi

	echo "[[./$File]]" >> "$foldertxt".md
	echo "[[+$File]]" >> "$foldertxt".md
done
