#!/bin/bash
f=$(basename "$1")
extens=${f##*.}
name=$(basename "$f" .$extens)
folder=$(echo ~/Gedankenspeicher/Archiv-Verschiebung/)
Newname=$(zenity --entry \
       --width 500 \
       --title "Den Dateinamen ändern?" \
       --text "Den Dateinamen ändern?" \
       --entry-text "$name")
File=$(echo "$Newname"."$extens" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g'|  sed 's/&/n/g' | sed 's/\///g' | sed 's/|//g' | sed 's/\[/(/g' | sed 's/\]/)/g' | sed 's/@/at/g')
mv "$1" "$folder""$File"
#File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g' |  sed 's/&/n/g' | sed 's/|//g' | sed 's/\[/(/g' | sed 's/\]/)/g' | sed 's/@/at/g')
#mv "$1" "$File"
f=$(basename "$File")

#f=$(basename "$1")
source=$(zenity --entry \
       --width 500 \
       --title "Noch eine Quelle hinzufügen?" \
       --text "Noch eine Quelle hinzufügen?" \
       --entry-text "$2")
#additiontext=$(yt-dlp --get-description ${source})
tags=$(zenity --entry \
       --width 500 \
       --title "Noch Schlagwörter hinzufügen?" \
       --text "Noch Schlagwörter hinzufügen?" \
       --entry-text "$4")
additiontext=$(zenity --entry \
       --width 500 \
       --title "Noch etwas hinzufügen?" \
       --text "Noch etwas hinzufügen?" \
       --entry-text "$3")
touch "$folder""$File".md
echo "Content-Type: text/x-zim-wiki" >> "$folder""$File".md
echo "Wiki-Format: zim 0.6" >> "$folder""$File".md
echo "[*] @VIDEO $tags **[[../$f]]** $source" >> "$folder""$File".md
echo "Text creation time:$(date +"[[Zettelkasten:%Y:%m:%d]]")" >> "$folder""$File".md
echo "Modification time:$(date +"[[Zettelkasten:%Y:%m:%d]]" -r "$folder""$File")" >> "$folder""$File".md
ffmpeg -loglevel quiet -ss 2 -i "$folder""$File" -t 1 -f image2 "$folder""$File".png
#convert "$folder""$File".png -resize 1200x1200 -quality 97 "$folder""$File"-px.png
#mv "$folder""$File"-px.png "$folder""$File".png
convert "$folder""$File".png "$folder""$File".avif
rm "$folder""$File".png
echo -e "[[../]]\n$additiontext\n" >> "$folder""$File".md
echo "{{../$f.avif?width=750}}" >> "$folder""$File".md
yt-dlp --get-description "$source" >> "$folder""$File".md
#echo "$3" >> "$File".md
#kate "$File".md 2>/dev/null &
