#!/bin/bash
ls --hide=*.txt "$1" > f
while read f
do
  filetxt=$(echo "$f" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
  filename=$(basename "$f")
  folder=$(date +"/home/christian/Gedankenspeicher/Gedankenspeicherwiki/Zettelkasten/%Y/%m/%d" -r "$1"/"$filename")
  mkdir -p $folder
  touch "$1"/"$filetxt".txt
  echo "Content-Type: text/x-zim-wiki" >> "$1"/"$filetxt".txt
  echo "Wiki-Format: zim 0.6" >> "$1"/"$filetxt".txt
  echo "[*] @BILD **[[../$filename]] $2**" >> "$1"/"$filetxt".txt
  echo "Text creation time:" >> "$1"/"$filetxt".txt
  date +"[[Zettelkasten:%Y:%m:%d]]" >> "$1"/"$filetxt".txt
  echo "Modification time:" >> "$1"/"$filetxt".txt
  date +"[[Zettelkasten:%Y:%m:%d]]" -r "$1"/"$filename" >> "$1"/"$filetxt".txt
  echo "{{../$filename?width=750}}" >> "$1"/"$filetxt".txt
  echo -e "[[../]]\n$2\n" >> "$1"/"$filetxt".txt
  mv "$1"/"$filename" "$folder"/"$filename"
  mv "$1"/"$filetxt".txt "$folder"/"$filetxt".txt
done < f
rm f

