#!/bin/bash
File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
f=$(basename "$1")
touch "$File".txt
echo "[ ] **[[../$f]]**" >> "$File".txt
cat "$2" >> "$File".txt
rm "$2"
