#!/bin/bash
File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
f=$(basename "$1")
folder=$(date +"/home/christian/Gedankenspeicher/Gedankenspeicherwiki/Zettelkasten/%Y/%m/%d" -r "$1")
mkdir -p $folder
touch "$File".md
echo "Content-Type: text/x-zim-wiki" >> "$File".md
echo "Wiki-Format: zim 0.6" >> "$File".md
echo "[*] @ARTIKEL **[[../$f]] >  2277-11-11 $2**" >> "$File".md
echo "Text creation time:" >> "$File".md
date +"[[Zettelkasten:%Y:%m:%d]]">> "$File".md
echo "Modification time:" >> "$File".md
date +"[[Zettelkasten:%Y:%m:%d]]" -r "$1" >> "$File".md
echo -e "[[../]]\n$2\n\n" >> "$File".md
pdfinfo "$1" | grep Pages >> "$File".md
echo -e "\n" >> "$File".md
pdftotext -f 1 -l 1 "$1" ->> "$File".md
mv "$1" $folder/"$1"
mv "$File".md $folder/"$File".md
ln -s $folder/"$1" "$f"
ln -s $folder/"$File".md "$File".md
echo "cd $folder"
#kate $folder/"$File".md 2>/dev/null &
#okular $folder/"$1" 2>/dev/null &
