#!/bin/bash

#case of input file is the original file
File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
f=$(basename "$1")
extens=${f##*.}
filename=${f%.*}

# case of input is md file
File2=$(basename "$1")
extens2=${File2##*.}
filename2=${File2%.*} #only the filename, here it is the original file
extens3=${filename2##*.}
#echo "${File2}"
#echo $extens2
#echo "${filename2}"
if [[ $extens2 == md ]]
then
	Newname=$(zenity --entry \
       --width 500 \
       --title "Type new filename" \
       --text "Enter new filename" \
       --entry-text "$(basename ${filename2} .$extens3)")
    if [ ! $? -eq 1 ];
    then
        Newname=$(echo "$Newname" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
        mv "$filename2" "$Newname"."$extens3"
        mv "${filename2%.*}" "$Newname"
        mv "${filename2%.*}"_files "$Newname"_files
        mv "${filename2%.*}"-Dateien "$Newname"-Dateien
        mv "${filename2%.*}"_Dateien "$Newname"_Dateien
        mv "$filename2".png "$Newname"."$extens3".png
        mv "$filename2".avif "$Newname"."$extens3".avif
        mv "$File2" "$Newname"."$extens3".md
        ttncc "$filename2" "$Newname"."$extens3"
        echo "$Newname"."$extens3"
    fi
else
	Newname=$(zenity --entry \
       --width 500 \
       --title "Type new filename" \
       --text "Enter new filename" \
       --entry-text "$filename")
    if [ ! $? -eq 1 ];
    then
        Newname=$(echo "$Newname" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
        mv "$f" "$Newname"."$extens"
        mv "$f" "$Newname"
        mv "${f%.*}" "$Newname"
        mv "${f%.*}"_files "$Newname"_files
        mv "${f%.*}"-Dateien "$Newname"-Dateien
        mv "${f%.*}"_Dateien "$Newname"_Dateien
        mv "$f".png "$Newname"."$extens".png
        mv "$f".avif "$Newname"."$extens".avif
        mv "$File".md "$Newname"."$extens".md
        ttncc "$f" "$Newname"."$extens"
        echo "$Newname"."$extens"
    fi
fi


