#!/bin/bash
source config.sh; # load the config library functions
journalDir="$(config_get journalDir)"


Zimtxt=$(date +"$journalDir/%Y/%m/%d.md" -r "$1")
file=$(basename "$1")
filetxt=$(basename "$1" | sed 's/\(.*\)\..*/\1/')
pathfile=$(realpath "$1" --relative-to=/home/christian)
pathfiletxt=$(realpath "$filetxt".md --relative-to=/home/christian)
touch "$Zimtxt"
echo -e "\n" >> "$Zimtxt"
echo [ ] ">2277-11-11" @VIDEO @VIDEOARCHIV "$2" "$file" [[~/"$pathfiletxt"]] ";" [[~/"$pathfile"]] >> "$Zimtxt"
echo -e "\nIST IM WIKI!!!" >> ~/"$pathfiletxt".md
