#!/bin/bash
File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
#f=$(basename "$1")
mv "$1" "$File"
f=$(basename "$File")
folder=$(date +"/home/christian/Gedankenspeicher/Gedankenspeicherwiki/Zettelkasten/%Y/%m/%d" -r "$f")
archivfolder="/home/christian/Gedankenspeicher/Archiv2/Videos"
mkdir -p $folder
if [[ -f "$File".txt ]]
then
	sed -i "3 i**Ins Archiv2 verschoben und verlinkt**" "$File".txt
else
	touch "$File".txt
	echo "Content-Type: text/x-zim-wiki" >> "$File".txt
	echo "Wiki-Format: zim 0.6" >> "$File".txt
	echo "[*] @ARCHIV2 @VIDEO **[[../$f]] $2**" >> "$File".txt
	echo "Text creation time: $(date +"[[Zettelkasten:%Y:%m:%d]]")" >> "$File".txt
	echo "Modification time: $(date +"[[Zettelkasten:%Y:%m:%d]]" -r "$f")" >> "$File".txt
	echo -e "[[../]]$2\nIns Archiv2 verschoben und verlinkt" >> "$File".txt
	ffmpeg -loglevel quiet -ss 2 -i "$File"  -t 1 -f image2 "$File".png
	convert "$File".png -resize 1200x1200 -quality 97 "$File"-px.png
  mv "$File"-px.png "$File".png
  echo "{{../$File.png?width=750}}" >> "$File".txt
fi
videostream=$(echo "/home/christian/Gedankenspeicher/Gedankenspeicherwiki/Zettelkasten/Gedankenwanderung/Zim-Arbeitsflaeche/Video_Stream.txt")
sed -i "10i
" "$videostream"
sed -i "10 s,^,[[$(date +"Zettelkasten:%Y:%m:%d" -r "$f"):$File]]," "$videostream"
sed -i "10i
" "$videostream"
sed -i "10 s,^,[[$archivfolder/"$File"]]," "$videostream"
sed -i "10i
" "$videostream"
mv "$f" $archivfolder/"$f"
mv "$File".txt $folder/"$File".txt
cp "$File".png $folder/"$File".png
mv "$File".png $archivfolder/"$File".png
ln -s $archivfolder/"$f" $folder/"$f"
ln -s $folder/"$File".txt $archivfolder/"$File".txt
echo "cd $folder"
zenity --info --text="Verschiebung fertig"
#kate $folder/"$File".txt 2>/dev/null &
