#!/bin/bash
Zimtxt=$(date +"/home/christian/Gedankenspeicher/Gedankenspeicherwiki/Zettelkasten/%Y/%m/%d.md" -r "$1")
file=$(basename "$1")
pathfile=$(realpath "$1" --relative-to=/home/christian)
pathfiletxt=$(echo "$pathfile" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g' )
touch "$Zimtxt"
echo -e "\n" >> "$Zimtxt"
echo [ ] ">2277-11-11" @VIDEO @VIDEOARCHIV "$2" "$file" [[~/"$pathfiletxt".md]] ";" [[~/"$pathfile"]] >> "$Zimtxt"
echo -e "\nIST IM WIKI!!!" >> ~/"$pathfiletxt".md
