#!/bin/bash
source config.sh; # load the config library functions
journalDir="$(config_get journalDir)"

folder=$(date +"$journalDir/%Y/%m/%d")
mkdir -p $folder
File=$(echo "$2" | sed 's/:/;/g')
wkhtmltoimage --enable-javascript --images "$1" $folder/"$File".png
ttpdf $folder/"$File".png "$1"

# --print-media-type
# --encoding utf8 --stop-slow-scripts --no-background --disable-forms --footer-center '[page]/[toPage]' -L 4cm -R 4cm --minimum-font-size 17
