@startwbs
+ tasks
 + Backlog
  + [ ] Anpassung bei beliebigen Dateinamen mit doppelten oder keiner Dateiendung
  + [ ] rewrite everything in english
  + [ ] write blog post for [website]()
  + [ ] using builtin `shell options` for [scripts]()
  + [ ] rewrite [tt-lib.sh]() with [subshell]() for optional output
  + [ ] Terminalabkürzung einführen für kate mit Journal öffnen
 + Doing (2)
  + [ ] latex `template files` in a separate folder [templates]()
  + [ ] write [documentation]()
   + [ ] make overview page about used tools,\n use for structuring the desktop files
    + [ ] describe main application
     + [ ] which [script]() do what
    + [ ] explain possible [workflows]() with used [scripts]()
@endwbs
