#!/bin/bash
source config.sh; # load the config library functions
journalDir="$(config_get journalDir)"
folder=$(date +"$journalDir/%Y/%m/%d")
mkdir -p $folder
cd $folder
gallery-dl --no-mtime --exec "tt {} '$1' " -D "$folder" "$1"
