#!/bin/bash
source config.sh; # load the config library functions
journalPage="$(config_get journalPage)"
source tt-lib.sh;

folder="$1"
folder=$(echo $folder | sed 's/\///g' | sed "s/ /\ /g")
list=$(ls -1 --hide=*.md "$folder")
lines="$(wc --lines <<< "$list")"

cd "$folder"
for (( i=$lines ; i>=1 ; i-- ));
do
	element=$(sed -n "${i}p" <(echo "$list"))
	#echo $(pwd)

	if [ ! -e "$File".md ];
	then
		tt "$element" "" "" "" "no"
	fi
done
