#!/bin/bash
#File=$(echo "$1" | sed 's/ /_/g' | sed 's/:/;/g'| sed -e "s/'/_/g" | sed 's/\"//g')
f=$(basename "$1" .md)
#extens=${f##*.} #only the extension of the file
filename=${f%.*} #only the filename
mkdir -p "$filename"
