#!/bin/bash
source config.sh; # load the config library functions
journalPage="$(config_get journalPage)"
journalDir="$(config_get journalDir)"
homeDir="$(config_get homeDir)"

Time=$(date +"$journalPage:%Y:%m:%d")
#folder=$(date +"$journalDir/%Y/%m/%d" -r "$1")
file="$homeDir/.config/zim/preferences.conf"
sed -i "206s/.*/marks=${Time}/" $file
sed -i "207s/.*/clips=${Time}/" $file
